// <auto-generated />
using System;
using LegacyBarber.App.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LegacyBarber.App.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702143857_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Archivo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BarberiaId")
                        .HasColumnType("bigint")
                        .HasColumnName("barberia_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<long?>("EntidadId")
                        .HasColumnType("bigint")
                        .HasColumnName("entidad_id");

                    b.Property<string>("EntidadTipo")
                        .HasColumnType("text")
                        .HasColumnName("entidad_tipo");

                    b.Property<string>("NombreAlmacenado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_almacenado");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_original");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ruta");

                    b.Property<long?>("TamanoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano_bytes");

                    b.Property<string>("TipoMime")
                        .HasColumnType("text")
                        .HasColumnName("tipo_mime");

                    b.HasKey("Id")
                        .HasName("pk_archivos");

                    b.HasIndex("BarberiaId")
                        .HasDatabaseName("ix_archivos_barberia_id");

                    b.ToTable("archivos", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Auditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accion");

                    b.Property<long>("BarberiaId")
                        .HasColumnType("bigint")
                        .HasColumnName("barberia_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("DatosAnteriores")
                        .HasColumnType("jsonb")
                        .HasColumnName("datos_anteriores");

                    b.Property<string>("DatosNuevos")
                        .HasColumnType("jsonb")
                        .HasColumnName("datos_nuevos");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<long>("RegistroId")
                        .HasColumnType("bigint")
                        .HasColumnName("registro_id");

                    b.Property<string>("Tabla")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tabla");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_auditorias");

                    b.HasIndex("BarberiaId")
                        .HasDatabaseName("ix_auditorias_barberia_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_auditorias_usuario_id");

                    b.ToTable("auditorias", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Barberia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Ciudad")
                        .HasColumnType("text")
                        .HasColumnName("ciudad");

                    b.Property<string>("Configuracion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("configuracion");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("en_configuracion")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaActivacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_activacion");

                    b.Property<string>("HorarioAtencion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("horario_atencion");

                    b.Property<long?>("LogoId")
                        .HasColumnType("bigint")
                        .HasColumnName("logo_id");

                    b.Property<string>("Nit")
                        .HasColumnType("text")
                        .HasColumnName("nit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_barberias");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_barberias_email");

                    b.HasIndex("LogoId")
                        .HasDatabaseName("ix_barberias_logo_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_barberias_slug");

                    b.ToTable("barberias", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Barbero", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<short?>("AniosExperiencia")
                        .HasColumnType("smallint")
                        .HasColumnName("anios_experiencia");

                    b.Property<long>("BarberiaId")
                        .HasColumnType("bigint")
                        .HasColumnName("barberia_id");

                    b.Property<string>("Biografia")
                        .HasColumnType("text")
                        .HasColumnName("biografia");

                    b.Property<decimal>("CalificacionPromedio")
                        .HasColumnType("numeric")
                        .HasColumnName("calificacion_promedio");

                    b.Property<decimal>("ComisionPorcentaje")
                        .HasColumnType("numeric")
                        .HasColumnName("comision_porcentaje");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Especialidades")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("especialidades");

                    b.Property<int>("TotalResenas")
                        .HasColumnType("integer")
                        .HasColumnName("total_resenas");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_barberos");

                    b.HasIndex("BarberiaId")
                        .HasDatabaseName("ix_barberos_barberia_id");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_barberos_usuario_id");

                    b.ToTable("barberos", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.BarberoServicio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<long>("BarberoId")
                        .HasColumnType("bigint")
                        .HasColumnName("barbero_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<decimal?>("PrecioPersonalizado")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_personalizado");

                    b.Property<long>("ServicioId")
                        .HasColumnType("bigint")
                        .HasColumnName("servicio_id");

                    b.HasKey("Id")
                        .HasName("pk_barbero_servicios");

                    b.HasIndex("ServicioId")
                        .HasDatabaseName("ix_barbero_servicios_servicio_id");

                    b.HasIndex("BarberoId", "ServicioId")
                        .IsUnique()
                        .HasDatabaseName("ix_barbero_servicios_barbero_id_servicio_id");

                    b.ToTable("barbero_servicios", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.CategoriaServicio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<long>("BarberiaId")
                        .HasColumnType("bigint")
                        .HasColumnName("barberia_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<short>("Orden")
                        .HasColumnType("smallint")
                        .HasColumnName("orden");

                    b.HasKey("Id")
                        .HasName("pk_categorias_servicios");

                    b.HasIndex("BarberiaId", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_categorias_servicios_barberia_id_nombre");

                    b.ToTable("categorias_servicios", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Cita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<long>("BarberiaId")
                        .HasColumnType("bigint")
                        .HasColumnName("barberia_id");

                    b.Property<long>("BarberoId")
                        .HasColumnType("bigint")
                        .HasColumnName("barbero_id");

                    b.Property<long?>("CanceladoPor")
                        .HasColumnType("bigint")
                        .HasColumnName("cancelado_por");

                    b.Property<long?>("CitaOriginalId")
                        .HasColumnType("bigint")
                        .HasColumnName("cita_original_id");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<short>("DuracionTotalMinutos")
                        .HasColumnType("smallint")
                        .HasColumnName("duracion_total_minutos");

                    b.Property<long>("EstadoCitaId")
                        .HasColumnType("bigint")
                        .HasColumnName("estado_cita_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval")
                        .HasColumnName("hora_fin");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("MotivoCancelacion")
                        .HasColumnType("text")
                        .HasColumnName("motivo_cancelacion");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origen");

                    b.Property<bool>("Pagado")
                        .HasColumnType("boolean")
                        .HasColumnName("pagado");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_total");

                    b.HasKey("Id")
                        .HasName("pk_citas");

                    b.HasIndex("BarberiaId")
                        .HasDatabaseName("ix_citas_barberia_id");

                    b.HasIndex("CitaOriginalId")
                        .HasDatabaseName("ix_citas_cita_original_id");

                    b.HasIndex("EstadoCitaId")
                        .HasDatabaseName("ix_citas_estado_cita_id");

                    b.HasIndex("ClienteId", "Fecha")
                        .HasDatabaseName("ix_citas_cliente_id_fecha");

                    b.HasIndex("BarberoId", "Fecha", "HoraInicio")
                        .HasDatabaseName("ix_citas_barbero_id_fecha_hora_inicio");

                    b.ToTable("citas", null, t =>
                        {
                            t.HasCheckConstraint("chk_cita_horas", "hora_inicio < hora_fin");
                        });
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.CitaServicio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CitaId")
                        .HasColumnType("bigint")
                        .HasColumnName("cita_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<short>("DuracionMinutos")
                        .HasColumnType("smallint")
                        .HasColumnName("duracion_minutos");

                    b.Property<decimal>("PrecioAplicado")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_aplicado");

                    b.Property<long>("ServicioId")
                        .HasColumnType("bigint")
                        .HasColumnName("servicio_id");

                    b.HasKey("Id")
                        .HasName("pk_cita_servicios");

                    b.HasIndex("ServicioId")
                        .HasDatabaseName("ix_cita_servicios_servicio_id");

                    b.HasIndex("CitaId", "ServicioId")
                        .IsUnique()
                        .HasDatabaseName("ix_cita_servicios_cita_id_servicio_id");

                    b.ToTable("cita_servicios", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BarberiaId")
                        .HasColumnType("bigint")
                        .HasColumnName("barberia_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<string>("Preferencias")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("preferencias");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_clientes_usuario_id");

                    b.HasIndex("BarberiaId", "UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_clientes_barberia_id_usuario_id");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Configuracion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<long>("BarberiaId")
                        .HasColumnType("bigint")
                        .HasColumnName("barberia_id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clave");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_configuraciones");

                    b.HasIndex("BarberiaId", "Clave")
                        .IsUnique()
                        .HasDatabaseName("ix_configuraciones_barberia_id_clave");

                    b.ToTable("configuraciones", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.EstadoCita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_estados_cita");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_estados_cita_nombre");

                    b.ToTable("estados_cita", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Color = "#D3B40E",
                            Descripcion = "Cita creada, esperando pago o confirmación",
                            Nombre = "pendiente"
                        },
                        new
                        {
                            Id = 2L,
                            Color = "#28c840",
                            Descripcion = "Cita confirmada",
                            Nombre = "confirmada"
                        },
                        new
                        {
                            Id = 3L,
                            Color = "#D3B40E",
                            Descripcion = "Cliente está siendo atendido",
                            Nombre = "en_curso"
                        },
                        new
                        {
                            Id = 4L,
                            Color = "#28c840",
                            Descripcion = "Servicio finalizado",
                            Nombre = "completada"
                        },
                        new
                        {
                            Id = 5L,
                            Color = "#ff5a5a",
                            Descripcion = "Cancelada por el cliente",
                            Nombre = "cancelada_por_cliente"
                        },
                        new
                        {
                            Id = 6L,
                            Color = "#ff5a5a",
                            Descripcion = "Cancelada por el barbero o admin",
                            Nombre = "cancelada_por_barbero"
                        },
                        new
                        {
                            Id = 7L,
                            Color = "#ff5a5a",
                            Descripcion = "Cancelada por no pago u otra regla",
                            Nombre = "cancelada_por_sistema"
                        },
                        new
                        {
                            Id = 8L,
                            Color = "#ff5a5a",
                            Descripcion = "Cliente no asistió",
                            Nombre = "no_show"
                        },
                        new
                        {
                            Id = 9L,
                            Color = "#D3B40E",
                            Descripcion = "Cita reprogramada, reemplazada por otra",
                            Nombre = "reprogramada"
                        });
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.ExcepcionHorario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BarberoId")
                        .HasColumnType("bigint")
                        .HasColumnName("barbero_id");

                    b.Property<bool>("EstaDisponible")
                        .HasColumnType("boolean")
                        .HasColumnName("esta_disponible");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<TimeSpan?>("HoraFin")
                        .HasColumnType("interval")
                        .HasColumnName("hora_fin");

                    b.Property<TimeSpan?>("HoraInicio")
                        .HasColumnType("interval")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.HasKey("Id")
                        .HasName("pk_excepciones_horarios");

                    b.HasIndex("BarberoId", "Fecha")
                        .IsUnique()
                        .HasDatabaseName("ix_excepciones_horarios_barbero_id_fecha");

                    b.ToTable("excepciones_horarios", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.HorarioBarbero", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<long>("BarberoId")
                        .HasColumnType("bigint")
                        .HasColumnName("barbero_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<short>("DiaSemana")
                        .HasColumnType("smallint")
                        .HasColumnName("dia_semana");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval")
                        .HasColumnName("hora_fin");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval")
                        .HasColumnName("hora_inicio");

                    b.HasKey("Id")
                        .HasName("pk_horarios_barberos");

                    b.HasIndex("BarberoId", "DiaSemana", "HoraInicio")
                        .IsUnique()
                        .HasDatabaseName("ix_horarios_barberos_barbero_id_dia_semana_hora_inicio");

                    b.ToTable("horarios_barberos", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.MetodoPago", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<long>("BarberiaId")
                        .HasColumnType("bigint")
                        .HasColumnName("barberia_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Configuracion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("configuracion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_metodos_pago");

                    b.HasIndex("BarberiaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_metodos_pago_barberia_id_codigo");

                    b.ToTable("metodos_pago", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Notificacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asunto");

                    b.Property<long>("BarberiaId")
                        .HasColumnType("bigint")
                        .HasColumnName("barberia_id");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canal");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenido");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Datos")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("datos");

                    b.Property<DateTime?>("EnviadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviada_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("LeidaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("leida_en");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_notificaciones");

                    b.HasIndex("BarberiaId")
                        .HasDatabaseName("ix_notificaciones_barberia_id");

                    b.HasIndex("UsuarioId", "Estado")
                        .HasDatabaseName("ix_notificaciones_usuario_id_estado")
                        .HasFilter("\"estado\" = 'pendiente'");

                    b.ToTable("notificaciones", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Pago", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<long>("BarberiaId")
                        .HasColumnType("bigint")
                        .HasColumnName("barberia_id");

                    b.Property<long>("CitaId")
                        .HasColumnType("bigint")
                        .HasColumnName("cita_id");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("DatosRespuesta")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("datos_respuesta");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<long>("MetodoPagoId")
                        .HasColumnType("bigint")
                        .HasColumnName("metodo_pago_id");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric")
                        .HasColumnName("monto");

                    b.Property<DateTime?>("PagadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pagado_en");

                    b.Property<DateTime?>("ReembolsadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reembolsado_en");

                    b.Property<string>("ReferenciaExterna")
                        .HasColumnType("text")
                        .HasColumnName("referencia_externa");

                    b.Property<long?>("RegistradoPor")
                        .HasColumnType("bigint")
                        .HasColumnName("registrado_por");

                    b.Property<string>("TransactionIdExterno")
                        .HasColumnType("text")
                        .HasColumnName("transaction_id_externo");

                    b.HasKey("Id")
                        .HasName("pk_pagos");

                    b.HasIndex("BarberiaId")
                        .HasDatabaseName("ix_pagos_barberia_id");

                    b.HasIndex("CitaId")
                        .HasDatabaseName("ix_pagos_cita_id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_pagos_cliente_id");

                    b.HasIndex("MetodoPagoId")
                        .HasDatabaseName("ix_pagos_metodo_pago_id");

                    b.HasIndex("RegistradoPor")
                        .HasDatabaseName("ix_pagos_registrado_por");

                    b.ToTable("pagos", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Resena", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BarberoId")
                        .HasColumnType("bigint")
                        .HasColumnName("barbero_id");

                    b.Property<short>("Calificacion")
                        .HasColumnType("smallint")
                        .HasColumnName("calificacion");

                    b.Property<long>("CitaId")
                        .HasColumnType("bigint")
                        .HasColumnName("cita_id");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Comentario")
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean")
                        .HasColumnName("visible");

                    b.HasKey("Id")
                        .HasName("pk_resenas");

                    b.HasIndex("BarberoId")
                        .HasDatabaseName("ix_resenas_barbero_id");

                    b.HasIndex("CitaId")
                        .IsUnique()
                        .HasDatabaseName("ix_resenas_cita_id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_resenas_cliente_id");

                    b.ToTable("resenas", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Rol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsSistema")
                        .HasColumnType("boolean")
                        .HasColumnName("es_sistema");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_nombre");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreadoEn = new DateTime(2026, 7, 2, 14, 38, 56, 938, DateTimeKind.Utc).AddTicks(356),
                            Descripcion = "Superadministrador del sistema Legacy Barber",
                            EsSistema = true,
                            Nombre = "superadmin"
                        },
                        new
                        {
                            Id = 2L,
                            CreadoEn = new DateTime(2026, 7, 2, 14, 38, 56, 938, DateTimeKind.Utc).AddTicks(362),
                            Descripcion = "Administrador de la barbería",
                            EsSistema = true,
                            Nombre = "admin"
                        },
                        new
                        {
                            Id = 3L,
                            CreadoEn = new DateTime(2026, 7, 2, 14, 38, 56, 938, DateTimeKind.Utc).AddTicks(363),
                            Descripcion = "Barbero que atiende citas",
                            EsSistema = true,
                            Nombre = "barbero"
                        },
                        new
                        {
                            Id = 4L,
                            CreadoEn = new DateTime(2026, 7, 2, 14, 38, 56, 938, DateTimeKind.Utc).AddTicks(363),
                            Descripcion = "Cliente que agenda citas",
                            EsSistema = true,
                            Nombre = "cliente"
                        });
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Servicio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<long>("BarberiaId")
                        .HasColumnType("bigint")
                        .HasColumnName("barberia_id");

                    b.Property<long?>("CategoriaId")
                        .HasColumnType("bigint")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<short>("DuracionMinutos")
                        .HasColumnType("smallint")
                        .HasColumnName("duracion_minutos");

                    b.Property<long?>("ImagenId")
                        .HasColumnType("bigint")
                        .HasColumnName("imagen_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric")
                        .HasColumnName("precio");

                    b.HasKey("Id")
                        .HasName("pk_servicios");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_servicios_categoria_id");

                    b.HasIndex("ImagenId")
                        .HasDatabaseName("ix_servicios_imagen_id");

                    b.HasIndex("BarberiaId", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_servicios_barberia_id_nombre");

                    b.ToTable("servicios", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.TokenRefresco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_tokens_refresco");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_tokens_refresco_token");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_tokens_refresco_usuario_id");

                    b.ToTable("tokens_refresco", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<long?>("BarberiaId")
                        .HasColumnType("bigint")
                        .HasColumnName("barberia_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerificado")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verificado");

                    b.Property<long?>("FotoId")
                        .HasColumnType("bigint")
                        .HasColumnName("foto_id");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("BarberiaId")
                        .HasDatabaseName("ix_usuarios_barberia_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("FotoId")
                        .HasDatabaseName("ix_usuarios_foto_id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<long>("RolId")
                        .HasColumnType("bigint")
                        .HasColumnName("rol_id");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_usuario_roles");

                    b.HasIndex("RolId")
                        .HasDatabaseName("ix_usuario_roles_rol_id");

                    b.HasIndex("UsuarioId", "RolId")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_roles_usuario_id_rol_id");

                    b.ToTable("usuario_roles", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Archivo", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barberia", "Barberia")
                        .WithMany("Archivos")
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_archivos_barberias_barberia_id");

                    b.Navigation("Barberia");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Auditoria", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barberia", "Barberia")
                        .WithMany("Auditorias")
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auditorias_barberias_barberia_id");

                    b.HasOne("LegacyBarber.App.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_auditorias_usuarios_usuario_id");

                    b.Navigation("Barberia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Barberia", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Archivo", "Logo")
                        .WithMany()
                        .HasForeignKey("LogoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_barberias_archivos_logo_id");

                    b.Navigation("Logo");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Barbero", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barberia", "Barberia")
                        .WithMany("Barberos")
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_barberos_barberias_barberia_id");

                    b.HasOne("LegacyBarber.App.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Barbero")
                        .HasForeignKey("LegacyBarber.App.Domain.Entities.Barbero", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_barberos_usuarios_usuario_id");

                    b.Navigation("Barberia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.BarberoServicio", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barbero", "Barbero")
                        .WithMany("BarberoServicios")
                        .HasForeignKey("BarberoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_barbero_servicios_barberos_barbero_id");

                    b.HasOne("LegacyBarber.App.Domain.Entities.Servicio", "Servicio")
                        .WithMany("BarberoServicios")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_barbero_servicios_servicios_servicio_id");

                    b.Navigation("Barbero");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.CategoriaServicio", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barberia", "Barberia")
                        .WithMany("CategoriasServicios")
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categorias_servicios_barberias_barberia_id");

                    b.Navigation("Barberia");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Cita", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barberia", "Barberia")
                        .WithMany("Citas")
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_citas_barberias_barberia_id");

                    b.HasOne("LegacyBarber.App.Domain.Entities.Barbero", "Barbero")
                        .WithMany("Citas")
                        .HasForeignKey("BarberoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_citas_barberos_barbero_id");

                    b.HasOne("LegacyBarber.App.Domain.Entities.Cita", "CitaOriginal")
                        .WithMany("Reprogramaciones")
                        .HasForeignKey("CitaOriginalId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_citas_citas_cita_original_id");

                    b.HasOne("LegacyBarber.App.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Citas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_citas_clientes_cliente_id");

                    b.HasOne("LegacyBarber.App.Domain.Entities.EstadoCita", "EstadoCita")
                        .WithMany("Citas")
                        .HasForeignKey("EstadoCitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_citas_estados_cita_estado_cita_id");

                    b.Navigation("Barberia");

                    b.Navigation("Barbero");

                    b.Navigation("CitaOriginal");

                    b.Navigation("Cliente");

                    b.Navigation("EstadoCita");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.CitaServicio", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Cita", "Cita")
                        .WithMany("CitaServicios")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cita_servicios_citas_cita_id");

                    b.HasOne("LegacyBarber.App.Domain.Entities.Servicio", "Servicio")
                        .WithMany("CitaServicios")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cita_servicios_servicios_servicio_id");

                    b.Navigation("Cita");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barberia", "Barberia")
                        .WithMany("Clientes")
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clientes_barberias_barberia_id");

                    b.HasOne("LegacyBarber.App.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Clientes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clientes_usuarios_usuario_id");

                    b.Navigation("Barberia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Configuracion", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barberia", "Barberia")
                        .WithMany("Configuraciones")
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_configuraciones_barberias_barberia_id");

                    b.Navigation("Barberia");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.ExcepcionHorario", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barbero", "Barbero")
                        .WithMany("ExcepcionesHorarios")
                        .HasForeignKey("BarberoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_excepciones_horarios_barberos_barbero_id");

                    b.Navigation("Barbero");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.HorarioBarbero", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barbero", "Barbero")
                        .WithMany("Horarios")
                        .HasForeignKey("BarberoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_horarios_barberos_barberos_barbero_id");

                    b.Navigation("Barbero");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.MetodoPago", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barberia", "Barberia")
                        .WithMany("MetodosPago")
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_metodos_pago_barberias_barberia_id");

                    b.Navigation("Barberia");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barberia", "Barberia")
                        .WithMany("Notificaciones")
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notificaciones_barberias_barberia_id");

                    b.HasOne("LegacyBarber.App.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notificaciones_usuarios_usuario_id");

                    b.Navigation("Barberia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Pago", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barberia", "Barberia")
                        .WithMany("Pagos")
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pagos_barberias_barberia_id");

                    b.HasOne("LegacyBarber.App.Domain.Entities.Cita", "Cita")
                        .WithMany("Pagos")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pagos_citas_cita_id");

                    b.HasOne("LegacyBarber.App.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Pagos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pagos_clientes_cliente_id");

                    b.HasOne("LegacyBarber.App.Domain.Entities.MetodoPago", "MetodoPago")
                        .WithMany("Pagos")
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pagos_metodos_pago_metodo_pago_id");

                    b.HasOne("LegacyBarber.App.Domain.Entities.Usuario", "UsuarioRegistrador")
                        .WithMany()
                        .HasForeignKey("RegistradoPor")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pagos_usuarios_registrado_por");

                    b.Navigation("Barberia");

                    b.Navigation("Cita");

                    b.Navigation("Cliente");

                    b.Navigation("MetodoPago");

                    b.Navigation("UsuarioRegistrador");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Resena", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barbero", "Barbero")
                        .WithMany("Resenas")
                        .HasForeignKey("BarberoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resenas_barberos_barbero_id");

                    b.HasOne("LegacyBarber.App.Domain.Entities.Cita", "Cita")
                        .WithOne("Resena")
                        .HasForeignKey("LegacyBarber.App.Domain.Entities.Resena", "CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resenas_citas_cita_id");

                    b.HasOne("LegacyBarber.App.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Resenas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resenas_clientes_cliente_id");

                    b.Navigation("Barbero");

                    b.Navigation("Cita");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Servicio", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barberia", "Barberia")
                        .WithMany("Servicios")
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_servicios_barberias_barberia_id");

                    b.HasOne("LegacyBarber.App.Domain.Entities.CategoriaServicio", "Categoria")
                        .WithMany("Servicios")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_servicios_categorias_servicios_categoria_id");

                    b.HasOne("LegacyBarber.App.Domain.Entities.Archivo", "Imagen")
                        .WithMany()
                        .HasForeignKey("ImagenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_servicios_archivos_imagen_id");

                    b.Navigation("Barberia");

                    b.Navigation("Categoria");

                    b.Navigation("Imagen");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.TokenRefresco", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Usuario", "Usuario")
                        .WithMany("TokensRefresco")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tokens_refresco_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barberia", "Barberia")
                        .WithMany("Usuarios")
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_usuarios_barberias_barberia_id");

                    b.HasOne("LegacyBarber.App.Domain.Entities.Archivo", "Foto")
                        .WithMany()
                        .HasForeignKey("FotoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_usuarios_archivos_foto_id");

                    b.Navigation("Barberia");

                    b.Navigation("Foto");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.UsuarioRol", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_roles_roles_rol_id");

                    b.HasOne("LegacyBarber.App.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_roles_usuarios_usuario_id");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Barberia", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("Auditorias");

                    b.Navigation("Barberos");

                    b.Navigation("CategoriasServicios");

                    b.Navigation("Citas");

                    b.Navigation("Clientes");

                    b.Navigation("Configuraciones");

                    b.Navigation("MetodosPago");

                    b.Navigation("Notificaciones");

                    b.Navigation("Pagos");

                    b.Navigation("Servicios");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Barbero", b =>
                {
                    b.Navigation("BarberoServicios");

                    b.Navigation("Citas");

                    b.Navigation("ExcepcionesHorarios");

                    b.Navigation("Horarios");

                    b.Navigation("Resenas");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.CategoriaServicio", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Cita", b =>
                {
                    b.Navigation("CitaServicios");

                    b.Navigation("Pagos");

                    b.Navigation("Reprogramaciones");

                    b.Navigation("Resena");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Pagos");

                    b.Navigation("Resenas");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.EstadoCita", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.MetodoPago", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Servicio", b =>
                {
                    b.Navigation("BarberoServicios");

                    b.Navigation("CitaServicios");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Barbero");

                    b.Navigation("Clientes");

                    b.Navigation("TokensRefresco");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
