// <auto-generated />
using System;
using LegacyBarber.App.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LegacyBarber.App.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Archivo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BarberiaId")
                        .HasColumnType("bigint")
                        .HasColumnName("barberia_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<long?>("EntidadId")
                        .HasColumnType("bigint")
                        .HasColumnName("entidad_id");

                    b.Property<string>("EntidadTipo")
                        .HasColumnType("text")
                        .HasColumnName("entidad_tipo");

                    b.Property<string>("NombreAlmacenado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_almacenado");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_original");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("TamanoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano_bytes");

                    b.Property<string>("TipoMime")
                        .HasColumnType("text")
                        .HasColumnName("tipo_mime");

                    b.HasKey("Id");

                    b.HasIndex("BarberiaId");

                    b.ToTable("archivos", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Auditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("BarberiaId")
                        .HasColumnType("bigint")
                        .HasColumnName("barberia_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("DatosAnteriores")
                        .HasColumnType("jsonb")
                        .HasColumnName("datos_anteriores");

                    b.Property<string>("DatosNuevos")
                        .HasColumnType("jsonb")
                        .HasColumnName("datos_nuevos");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<long>("RegistroId")
                        .HasColumnType("bigint")
                        .HasColumnName("registro_id");

                    b.Property<string>("Tabla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("BarberiaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Barberia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Configuracion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HorarioAtencion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<long?>("LogoId")
                        .HasColumnType("bigint")
                        .HasColumnName("logo_id");

                    b.Property<string>("Nit")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LogoId");

                    b.ToTable("barberias", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Barbero", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<short?>("AniosExperiencia")
                        .HasColumnType("smallint")
                        .HasColumnName("anios_experiencia");

                    b.Property<long>("BarberiaId")
                        .HasColumnType("bigint")
                        .HasColumnName("barberia_id");

                    b.Property<string>("Biografia")
                        .HasColumnType("text");

                    b.Property<decimal>("CalificacionPromedio")
                        .HasColumnType("numeric")
                        .HasColumnName("calificacion_promedio");

                    b.Property<decimal>("ComisionPorcentaje")
                        .HasColumnType("numeric")
                        .HasColumnName("comision_porcentaje");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Especialidades")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]");

                    b.Property<int>("TotalResenas")
                        .HasColumnType("integer")
                        .HasColumnName("total_resenas");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("BarberiaId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("barberos", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.BarberoServicio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<long>("BarberoId")
                        .HasColumnType("bigint")
                        .HasColumnName("barbero_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<decimal?>("PrecioPersonalizado")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_personalizado");

                    b.Property<long>("ServicioId")
                        .HasColumnType("bigint")
                        .HasColumnName("servicio_id");

                    b.HasKey("Id");

                    b.HasIndex("ServicioId");

                    b.HasIndex("BarberoId", "ServicioId")
                        .IsUnique();

                    b.ToTable("barbero_servicios", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.CategoriaServicio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<long>("BarberiaId")
                        .HasColumnType("bigint")
                        .HasColumnName("barberia_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("Orden")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("BarberiaId", "Nombre")
                        .IsUnique();

                    b.ToTable("categorias_servicios", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Cita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<long>("BarberiaId")
                        .HasColumnType("bigint")
                        .HasColumnName("barberia_id");

                    b.Property<long>("BarberoId")
                        .HasColumnType("bigint")
                        .HasColumnName("barbero_id");

                    b.Property<long?>("CanceladoPor")
                        .HasColumnType("bigint")
                        .HasColumnName("cancelado_por");

                    b.Property<long?>("CitaOriginalId")
                        .HasColumnType("bigint")
                        .HasColumnName("cita_original_id");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<short>("DuracionTotalMinutos")
                        .HasColumnType("smallint")
                        .HasColumnName("duracion_total_minutos");

                    b.Property<long>("EstadoCitaId")
                        .HasColumnType("bigint")
                        .HasColumnName("estado_cita_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval")
                        .HasColumnName("hora_fin");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("MotivoCancelacion")
                        .HasColumnType("text")
                        .HasColumnName("motivo_cancelacion");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Pagado")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_total");

                    b.HasKey("Id");

                    b.HasIndex("BarberiaId");

                    b.HasIndex("CitaOriginalId");

                    b.HasIndex("EstadoCitaId");

                    b.HasIndex("ClienteId", "Fecha");

                    b.HasIndex("BarberoId", "Fecha", "HoraInicio");

                    b.ToTable("citas", null, t =>
                        {
                            t.HasCheckConstraint("chk_cita_horas", "hora_inicio < hora_fin");
                        });
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.CitaServicio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CitaId")
                        .HasColumnType("bigint")
                        .HasColumnName("cita_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<short>("DuracionMinutos")
                        .HasColumnType("smallint")
                        .HasColumnName("duracion_minutos");

                    b.Property<decimal>("PrecioAplicado")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_aplicado");

                    b.Property<long>("ServicioId")
                        .HasColumnType("bigint")
                        .HasColumnName("servicio_id");

                    b.HasKey("Id");

                    b.HasIndex("ServicioId");

                    b.HasIndex("CitaId", "ServicioId")
                        .IsUnique();

                    b.ToTable("cita_servicios", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BarberiaId")
                        .HasColumnType("bigint")
                        .HasColumnName("barberia_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<string>("Preferencias")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.HasIndex("BarberiaId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Configuracion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<long>("BarberiaId")
                        .HasColumnType("bigint")
                        .HasColumnName("barberia_id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("BarberiaId", "Clave")
                        .IsUnique();

                    b.ToTable("configuraciones", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.EstadoCita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("estados_cita", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Color = "#D3B40E",
                            Descripcion = "Cita creada, esperando pago o confirmación",
                            Nombre = "pendiente"
                        },
                        new
                        {
                            Id = 2L,
                            Color = "#28c840",
                            Descripcion = "Cita confirmada",
                            Nombre = "confirmada"
                        },
                        new
                        {
                            Id = 3L,
                            Color = "#D3B40E",
                            Descripcion = "Cliente está siendo atendido",
                            Nombre = "en_curso"
                        },
                        new
                        {
                            Id = 4L,
                            Color = "#28c840",
                            Descripcion = "Servicio finalizado",
                            Nombre = "completada"
                        },
                        new
                        {
                            Id = 5L,
                            Color = "#ff5a5a",
                            Descripcion = "Cancelada por el cliente",
                            Nombre = "cancelada_por_cliente"
                        },
                        new
                        {
                            Id = 6L,
                            Color = "#ff5a5a",
                            Descripcion = "Cancelada por el barbero o admin",
                            Nombre = "cancelada_por_barbero"
                        },
                        new
                        {
                            Id = 7L,
                            Color = "#ff5a5a",
                            Descripcion = "Cancelada por no pago u otra regla",
                            Nombre = "cancelada_por_sistema"
                        },
                        new
                        {
                            Id = 8L,
                            Color = "#ff5a5a",
                            Descripcion = "Cliente no asistió",
                            Nombre = "no_show"
                        },
                        new
                        {
                            Id = 9L,
                            Color = "#D3B40E",
                            Descripcion = "Cita reprogramada, reemplazada por otra",
                            Nombre = "reprogramada"
                        });
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.ExcepcionHorario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BarberoId")
                        .HasColumnType("bigint")
                        .HasColumnName("barbero_id");

                    b.Property<bool>("EstaDisponible")
                        .HasColumnType("boolean")
                        .HasColumnName("esta_disponible");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("HoraFin")
                        .HasColumnType("interval")
                        .HasColumnName("hora_fin");

                    b.Property<TimeSpan?>("HoraInicio")
                        .HasColumnType("interval")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("Motivo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BarberoId", "Fecha")
                        .IsUnique();

                    b.ToTable("excepciones_horarios", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.HorarioBarbero", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<long>("BarberoId")
                        .HasColumnType("bigint")
                        .HasColumnName("barbero_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<short>("DiaSemana")
                        .HasColumnType("smallint")
                        .HasColumnName("dia_semana");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval")
                        .HasColumnName("hora_fin");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval")
                        .HasColumnName("hora_inicio");

                    b.HasKey("Id");

                    b.HasIndex("BarberoId", "DiaSemana", "HoraInicio")
                        .IsUnique();

                    b.ToTable("horarios_barberos", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.MetodoPago", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<long>("BarberiaId")
                        .HasColumnType("bigint")
                        .HasColumnName("barberia_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Configuracion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BarberiaId", "Codigo")
                        .IsUnique();

                    b.ToTable("metodos_pago", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Notificacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("BarberiaId")
                        .HasColumnType("bigint")
                        .HasColumnName("barberia_id");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Datos")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<DateTime?>("EnviadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviada_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("LeidaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("leida_en");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("BarberiaId");

                    b.HasIndex("UsuarioId", "Estado")
                        .HasFilter("\"estado\" = 'pendiente'");

                    b.ToTable("notificaciones", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Pago", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<long>("BarberiaId")
                        .HasColumnType("bigint")
                        .HasColumnName("barberia_id");

                    b.Property<long?>("BarberoId")
                        .HasColumnType("bigint");

                    b.Property<long>("CitaId")
                        .HasColumnType("bigint")
                        .HasColumnName("cita_id");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("DatosRespuesta")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("datos_respuesta");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("MetodoPagoId")
                        .HasColumnType("bigint")
                        .HasColumnName("metodo_pago_id");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("PagadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pagado_en");

                    b.Property<DateTime?>("ReembolsadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reembolsado_en");

                    b.Property<string>("ReferenciaExterna")
                        .HasColumnType("text")
                        .HasColumnName("referencia_externa");

                    b.Property<long?>("RegistradoPor")
                        .HasColumnType("bigint")
                        .HasColumnName("registrado_por");

                    b.Property<string>("TransactionIdExterno")
                        .HasColumnType("text")
                        .HasColumnName("transaction_id_externo");

                    b.HasKey("Id");

                    b.HasIndex("BarberiaId");

                    b.HasIndex("BarberoId");

                    b.HasIndex("CitaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("RegistradoPor");

                    b.ToTable("pagos", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Resena", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BarberoId")
                        .HasColumnType("bigint")
                        .HasColumnName("barbero_id");

                    b.Property<short>("Calificacion")
                        .HasColumnType("smallint");

                    b.Property<long>("CitaId")
                        .HasColumnType("bigint")
                        .HasColumnName("cita_id");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BarberoId");

                    b.HasIndex("CitaId")
                        .IsUnique();

                    b.HasIndex("ClienteId");

                    b.ToTable("resenas", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Rol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("EsSistema")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreadoEn = new DateTime(2026, 6, 27, 16, 34, 11, 206, DateTimeKind.Utc).AddTicks(5644),
                            Descripcion = "Superadministrador del sistema Legacy Barber",
                            EsSistema = true,
                            Nombre = "superadmin"
                        },
                        new
                        {
                            Id = 2L,
                            CreadoEn = new DateTime(2026, 6, 27, 16, 34, 11, 206, DateTimeKind.Utc).AddTicks(5647),
                            Descripcion = "Administrador de la barbería",
                            EsSistema = true,
                            Nombre = "admin"
                        },
                        new
                        {
                            Id = 3L,
                            CreadoEn = new DateTime(2026, 6, 27, 16, 34, 11, 206, DateTimeKind.Utc).AddTicks(5648),
                            Descripcion = "Barbero que atiende citas",
                            EsSistema = true,
                            Nombre = "barbero"
                        },
                        new
                        {
                            Id = 4L,
                            CreadoEn = new DateTime(2026, 6, 27, 16, 34, 11, 206, DateTimeKind.Utc).AddTicks(5648),
                            Descripcion = "Cliente que agenda citas",
                            EsSistema = true,
                            Nombre = "cliente"
                        });
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Servicio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<long>("BarberiaId")
                        .HasColumnType("bigint")
                        .HasColumnName("barberia_id");

                    b.Property<long?>("CategoriaId")
                        .HasColumnType("bigint")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<short>("DuracionMinutos")
                        .HasColumnType("smallint")
                        .HasColumnName("duracion_minutos");

                    b.Property<long?>("ImagenId")
                        .HasColumnType("bigint")
                        .HasColumnName("imagen_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ImagenId");

                    b.HasIndex("BarberiaId", "Nombre")
                        .IsUnique();

                    b.ToTable("servicios", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.TokenRefresco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("tokens_refresco", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<long?>("BarberiaId")
                        .HasColumnType("bigint")
                        .HasColumnName("barberia_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<bool>("EmailVerificado")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verificado");

                    b.Property<long?>("FotoId")
                        .HasColumnType("bigint")
                        .HasColumnName("foto_id");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso");

                    b.HasKey("Id");

                    b.HasIndex("FotoId");

                    b.HasIndex("BarberiaId", "Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<long>("RolId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId", "RolId")
                        .IsUnique();

                    b.ToTable("usuario_roles", (string)null);
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Archivo", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barberia", "Barberia")
                        .WithMany("Archivos")
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barberia");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Auditoria", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barberia", "Barberia")
                        .WithMany("Auditorias")
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegacyBarber.App.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Barberia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Barberia", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Archivo", "Logo")
                        .WithMany()
                        .HasForeignKey("LogoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Logo");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Barbero", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barberia", "Barberia")
                        .WithMany("Barberos")
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegacyBarber.App.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Barbero")
                        .HasForeignKey("LegacyBarber.App.Domain.Entities.Barbero", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barberia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.BarberoServicio", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barbero", "Barbero")
                        .WithMany("BarberoServicios")
                        .HasForeignKey("BarberoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegacyBarber.App.Domain.Entities.Servicio", "Servicio")
                        .WithMany("BarberoServicios")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barbero");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.CategoriaServicio", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barberia", "Barberia")
                        .WithMany("CategoriasServicios")
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barberia");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Cita", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barberia", "Barberia")
                        .WithMany("Citas")
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegacyBarber.App.Domain.Entities.Barbero", "Barbero")
                        .WithMany("Citas")
                        .HasForeignKey("BarberoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegacyBarber.App.Domain.Entities.Cita", "CitaOriginal")
                        .WithMany("Reprogramaciones")
                        .HasForeignKey("CitaOriginalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LegacyBarber.App.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Citas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegacyBarber.App.Domain.Entities.EstadoCita", "EstadoCita")
                        .WithMany("Citas")
                        .HasForeignKey("EstadoCitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Barberia");

                    b.Navigation("Barbero");

                    b.Navigation("CitaOriginal");

                    b.Navigation("Cliente");

                    b.Navigation("EstadoCita");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.CitaServicio", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Cita", "Cita")
                        .WithMany("CitaServicios")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegacyBarber.App.Domain.Entities.Servicio", "Servicio")
                        .WithMany("CitaServicios")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barberia", "Barberia")
                        .WithMany("Clientes")
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegacyBarber.App.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Cliente")
                        .HasForeignKey("LegacyBarber.App.Domain.Entities.Cliente", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barberia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Configuracion", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barberia", "Barberia")
                        .WithMany("Configuraciones")
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barberia");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.ExcepcionHorario", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barbero", "Barbero")
                        .WithMany("ExcepcionesHorarios")
                        .HasForeignKey("BarberoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barbero");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.HorarioBarbero", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barbero", "Barbero")
                        .WithMany("Horarios")
                        .HasForeignKey("BarberoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barbero");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.MetodoPago", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barberia", "Barberia")
                        .WithMany("MetodosPago")
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barberia");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barberia", "Barberia")
                        .WithMany("Notificaciones")
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegacyBarber.App.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barberia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Pago", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barberia", "Barberia")
                        .WithMany("Pagos")
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegacyBarber.App.Domain.Entities.Barbero", null)
                        .WithMany("Pagos")
                        .HasForeignKey("BarberoId");

                    b.HasOne("LegacyBarber.App.Domain.Entities.Cita", "Cita")
                        .WithMany("Pagos")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegacyBarber.App.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Pagos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegacyBarber.App.Domain.Entities.MetodoPago", "MetodoPago")
                        .WithMany("Pagos")
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegacyBarber.App.Domain.Entities.Usuario", "UsuarioRegistrador")
                        .WithMany()
                        .HasForeignKey("RegistradoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Barberia");

                    b.Navigation("Cita");

                    b.Navigation("Cliente");

                    b.Navigation("MetodoPago");

                    b.Navigation("UsuarioRegistrador");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Resena", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barbero", "Barbero")
                        .WithMany("Resenas")
                        .HasForeignKey("BarberoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegacyBarber.App.Domain.Entities.Cita", "Cita")
                        .WithOne("Resena")
                        .HasForeignKey("LegacyBarber.App.Domain.Entities.Resena", "CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegacyBarber.App.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Resenas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Barbero");

                    b.Navigation("Cita");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Servicio", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barberia", "Barberia")
                        .WithMany("Servicios")
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegacyBarber.App.Domain.Entities.CategoriaServicio", "Categoria")
                        .WithMany("Servicios")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LegacyBarber.App.Domain.Entities.Archivo", "Imagen")
                        .WithMany()
                        .HasForeignKey("ImagenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Barberia");

                    b.Navigation("Categoria");

                    b.Navigation("Imagen");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.TokenRefresco", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Usuario", "Usuario")
                        .WithMany("TokensRefresco")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Barberia", "Barberia")
                        .WithMany("Usuarios")
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LegacyBarber.App.Domain.Entities.Archivo", "Foto")
                        .WithMany()
                        .HasForeignKey("FotoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Barberia");

                    b.Navigation("Foto");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.UsuarioRol", b =>
                {
                    b.HasOne("LegacyBarber.App.Domain.Entities.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegacyBarber.App.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Barberia", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("Auditorias");

                    b.Navigation("Barberos");

                    b.Navigation("CategoriasServicios");

                    b.Navigation("Citas");

                    b.Navigation("Clientes");

                    b.Navigation("Configuraciones");

                    b.Navigation("MetodosPago");

                    b.Navigation("Notificaciones");

                    b.Navigation("Pagos");

                    b.Navigation("Servicios");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Barbero", b =>
                {
                    b.Navigation("BarberoServicios");

                    b.Navigation("Citas");

                    b.Navigation("ExcepcionesHorarios");

                    b.Navigation("Horarios");

                    b.Navigation("Pagos");

                    b.Navigation("Resenas");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.CategoriaServicio", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Cita", b =>
                {
                    b.Navigation("CitaServicios");

                    b.Navigation("Pagos");

                    b.Navigation("Reprogramaciones");

                    b.Navigation("Resena");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Pagos");

                    b.Navigation("Resenas");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.EstadoCita", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.MetodoPago", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Servicio", b =>
                {
                    b.Navigation("BarberoServicios");

                    b.Navigation("CitaServicios");
                });

            modelBuilder.Entity("LegacyBarber.App.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Barbero");

                    b.Navigation("Cliente");

                    b.Navigation("TokensRefresco");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
